version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "mtebusi"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/addon"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "mtebusi"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "mtebusi"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"