build_from:
  amd64: "homeassistant/amd64-base-python:3.12-alpine"
  aarch64: "homeassistant/aarch64-base-python:3.12-alpine"
  armhf: "homeassistant/armhf-base-python:3.12-alpine"
  armv7: "homeassistant/armv7-base-python:3.12-alpine"
  i386: "homeassistant/i386-base-python:3.12-alpine"
args:
  TEMPIO_VERSION: "2021.09.0"