build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.12"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12"
  i386: "ghcr.io/home-assistant/i386-base-python:3.12"
args:
  TEMPIO_VERSION: "2021.09.0"