name: Build and Publish Add-on

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        arch: [amd64, aarch64, armhf, armv7, i386]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get addon version
        id: version
        run: |
          VERSION=$(grep "^version:" addon/config.yaml | cut -d'"' -f2)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building addon version: ${VERSION}"
      
      - name: Determine base image
        id: base
        run: |
          case "${{ matrix.arch }}" in
            amd64)   echo "image=ghcr.io/home-assistant/amd64-base:latest" >> $GITHUB_OUTPUT ;;
            aarch64) echo "image=ghcr.io/home-assistant/aarch64-base:latest" >> $GITHUB_OUTPUT ;;
            armhf)   echo "image=ghcr.io/home-assistant/armhf-base:latest" >> $GITHUB_OUTPUT ;;
            armv7)   echo "image=ghcr.io/home-assistant/armv7-base:latest" >> $GITHUB_OUTPUT ;;
            i386)    echo "image=ghcr.io/home-assistant/i386-base:latest" >> $GITHUB_OUTPUT ;;
          esac
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: addon/
          file: addon/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.arch }}-ha-mcp-v2:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.arch }}-ha-mcp-v2:${{ steps.version.outputs.version }}
          build-args: |
            BUILD_FROM=${{ steps.base.outputs.image }}
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_DATE=${{ github.run_id }}
            BUILD_REF=${{ github.sha }}
            BUILD_VERSION=${{ steps.version.outputs.version }}
            BUILD_NAME=HomeAssistant MCP Server
            BUILD_DESCRIPTION=MCP server for Claude Desktop integration
            BUILD_REPOSITORY=${{ github.repository }}
  
