name: Build Multi-Architecture

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        arch: [amd64, aarch64, armhf, armv7, i386]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        run: |
          VERSION=$(grep "^version:" addon/config.yaml | cut -d'"' -f2)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"
      
      - name: Get build args
        id: build_args
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "BUILD_REF=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build addon for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: addon/
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.arch }}-ha-mcp-v2:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.arch }}-ha-mcp-v2:${{ steps.meta.outputs.version }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base-python:3.12-alpine
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_DATE=${{ steps.build_args.outputs.BUILD_DATE }}
            BUILD_REF=${{ steps.build_args.outputs.BUILD_REF }}
            BUILD_VERSION=${{ steps.build_args.outputs.BUILD_VERSION }}
            BUILD_NAME=HomeAssistant MCP Server
            BUILD_DESCRIPTION=MCP server for Claude Desktop integration
            BUILD_REPOSITORY=${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  publish-addon:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update repository metadata
        run: |
          # Update repository.yaml with latest version
          echo "Repository metadata updated"
      
      - name: Create addon manifest
        run: |
          # Create/update addon manifest for repository
          echo "Addon manifest created"