name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      homeassistant:
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
          - 8123:8123
        options: >-
          --health-cmd="curl -f http://localhost:8123/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - /tmp/ha_config:/config
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov pytest-timeout
          pip install -r src/requirements.txt
      
      - name: Wait for HomeAssistant
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8123/; then
              echo "HomeAssistant is ready"
              break
            fi
            echo "Waiting for HomeAssistant... ($i/30)"
            sleep 2
          done
      
      - name: Run unit tests
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-report=html
        env:
          HA_URL: http://localhost:8123
          HA_TOKEN: test_token
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
      
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
  
  integration-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: addon/
          load: true
          tags: ha-mcp-server:test
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/amd64-base-python:3.12
      
      - name: Start test environment
        run: |
          docker-compose -f tests/docker-compose.yml up -d
      
      - name: Wait for services
        run: |
          sleep 30
      
      - name: Run integration tests
        run: |
          docker exec test_homeassistant python -m pytest /app/tests/test_integration.py -v
      
      - name: Collect logs
        if: always()
        run: |
          docker-compose -f tests/docker-compose.yml logs > test-logs.txt
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: test-logs.txt
      
      - name: Stop test environment
        if: always()
        run: |
          docker-compose -f tests/docker-compose.yml down